name: Feature Request
description: Suggest a new feature or enhancement for Continuum
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see added to Continuum.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which part of Continuum does this relate to?
      options:
        - Printer Management
        - Network/Redirects
        - Health Monitoring
        - Job Tracking
        - Workflows/Automation
        - Web UI
        - API
        - Authentication
        - Notifications
        - System/Installation
        - Other
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples about the feature request
    validations:
      required: false
